

export const environment = {
  production: false,
  '//Global Variables': '------------------ Global Find GetActive -------------------------',
  'find': 'Find',
  'FindActive':'FindActive',
  'getActive': 'GetActive',
  '//Catalyst': '------------------Catalyst APIs path-------------------------',
  'catalyst_api_url': 'https://gateway.microserviceone.com/',
  'GetDiluentSize': 'GetDiluentSize',
  'catalystShape': 'api/CatalystShape',
  'catalystSizes': 'api/CatalystSize',
  'catalystScale': 'api/CatalystScale',
  'catalystAlias': 'api/catalystAlias',
  'catalystFamily': 'api/CatalystFamily',
  'catalystFamilyActive': 'api/CatalystFamily/GetActive',
  'catalystState': 'api/CatalystState',
  'catalystApplication': 'api/CatalystApplication',
  'catalystDiluents': 'api/CatalystDiluents',
  'catalystDulientSize': 'CatalystDulientSize',
  'catalystType': 'api/CatalystType',
  'catalystApplicationDetails': 'api/CatalystApplicationDetails',
  'catalystApplicationByTypeId': 'api/CatalystApplication/GetAllCatalystApplicationsByType',
  'catalystLoadingTemplate': 'api/CatalystLoadingTemplate',
  'catalystInventory': 'api/CatalystInventory/GetAllCatalystInventoriesByTechnology',
  'inventory': 'api/CatalystInventory',
  'status': 'Status',
  'catalystMain': 'api/CatalystMain',
  'getStates': 'GetStates',
  'getAlias': 'GetAlias',
  'getFamily': 'GetFamily',
  '//Plant': '------------------Plant APIs path-------------------------',
  'plants_api_url': 'https://gateway.microserviceone.com/',
  'plants': 'api/Plants',
  'activePalnts': 'FindActivePlant',
  'building': 'api/Building',
  'getBuildingByLocationName': 'GetBuildingsByLocation',
  'equipments': 'api/Equipments',
  'getCalibrationBYEquipment': 'GetCalibrationByEquipment',
  'getAllEquipmentType': 'GetAllEquipmentType',
  'getAllCalculationModule': 'GetAllCalculationModule',
  'getAllVCFType': 'GetAllVCFType',
  'getCalculationByEquipmentType': 'GetCalculationByEquipmentType',
  'location': 'api/Location',
  'equipmentCalibration': 'api/EquipmentCalibration',
  'getCaliBrationFactor': 'GetCaliBrationFactor',
  'getCalibrationFactor': 'GetCalibrationFactor',
  '//Project': '------------------Project APIs path-------------------------',
  'project_api_url': 'https://gateway.microserviceone.com/',
  'project': 'api/Project',
  'getProjectsByType': 'GetProjectsByType',
  'updateProject': 'UpdateProject',
  'currentPhasePriority': 'CurrentPhasePriority',
  'currentPhaseName': 'CurrentPhaseName',
  'ppPriority': 'PPPriority',
  'getUOPSegment': 'GetUOPSegment',
  'addProject': 'AddProject',
  'projectType': 'ProjectType',
  'BusinessJustification': 'BusinessJustification',
  'businessObjective': 'BusinessObjective',
  'businessGroup': 'BusinessGroup',
  'getFile': 'GetFile',
  'getProjectFiles': 'GetProjectFiles',
  'getProjectApplication': 'GetProjectApplication',
  '//Lims': '------------------Project APIs path-------------------------',
  'lims_analysis_api_url': 'https://gateway.microserviceone.com/',

  'limsAnalysis': 'api/LIMSAnalysis',
  'sourceName': 'SourceName',
  'limsComponent': 'api/LimsAnalysisComponent',
  'getLimsComponent': 'GetLIMSAnalysisMethodComponentData',
  'saveLimsComponent': 'SaveLIMSAnalysisMethodComponent',
  'deleteLimsComponent': 'DeleteComponentData',
  'findLIMSOperation': 'FindLIMSOperation',
  'limsOperations': 'Limsoperation',
  'LimsStandardComponents': 'Limscomponent',

  'saveLIMSAnalysisMethodData': 'SaveLIMSAnalysisMethodData',
  'deleteMethodData': 'DeleteMethodData',
  '//lims_New': '-------------------------------new----------------',

  'analysisMethod': 'api/AnalysisMethod',
  'getLIMSAnalysisMethodData': 'GetLIMSAnalysisMethodData',
  'getLimsSources': 'GetLimsSources',
  'getAnalysisMethodByNameAsync': 'GetAnalysisMethodByNameAsync',
  'uomGroup': 'UOMGroup',
  'uomComponent': 'api/UOM',
  'GetUomsByGroup': 'GetUomsByGroup',
  '// Manage raw material': '---------------- Manage Common API path ---------------',
  'raw_material_url': 'https://gateway.microserviceone.com/',
  'manageRawMaterial': 'api/RawMaterial',
  'rawMaterialState': 'api/RawMaterialState',
  'rawMaterialStateActive': 'api/RawMaterial/GetActiveRawMaterial',
  'synthesizedActive': 'api/RawMaterial/GetActiveSynthesizedMaterial',
  'FindActiveMaterial': 'FindActiveMaterial',
  '//Manage Common': '------------------Manage Common API path-------------------------',
  'user_api_url': 'https://gateway.microserviceone.com/',
  'findLead': 'FindTeamLeads',
  'uom_api_url': 'https://gateway.microserviceone.com/',
  'runObjectives_api_url': 'https://gateway.microserviceone.com/',
  'manageUom': 'api/uom',
  'manageUomGetActive': 'api/UOM/GetActive',

  "activeRole": "api/Roles/GetActive",
  "activeTechnology": "api/Technology/GetActive",
  'gettechnologies': 'api/User/GetTechnologies',
  'getSuperAdminTechnologies': 'api/technology',
  'getroles': 'api/User/GetRoles',
  'activeroles': 'api/Roles/GetActive',
  '//Manage Technology': '------------------Manage Technology API path-------------------------',
  'menu_api_url': 'https://gateway.microserviceone.com/',
  '//Manage Technology URL': '------------------Manage Technology URL-------------------------',
  'manageTechnology': 'api/technology',
  'runObjective': 'api/ProductObjective',
  'runObjectiveAscending': 'api/ProductObjective/GetActive',
  'process': 'api/Process',
  'standardCutBoilingPoint': 'api/StandardCutBoilingPoint',
  'updateBoilingPoints': 'Update',
  'getCutBolingPoints': 'GetStandardCutBoilingPoints',
  'recipe_api_url': 'https://gateway.microserviceone.com/',
  'manageRecipe': 'api/Recipe',
  '//Manage User URL': '------------------Manage User URL-------------------------',
  'manageUser': 'api/User',
  'Department': 'api/Department',
  'getDepartment': 'GetDepartment',
  'technologyRole': 'TechnologyRole',
  'getTeamLeads': 'GetTeamLeads',
  'teamLeads': 'TeamLeads',
  'superAdmin': 'isSuperAdmin=',
  '//Manage Roles URL': '------------------Manage Roles URL-------------------------',
  'manageRoles': 'api/Roles',
  '//Manage Privileges URL': '------------------Manage Privileges URL-------------------------',
  'managePrivileges': 'api/UserPrivileges',
  '//Manage Unit Of Measurement URL': '------------------Manage Unit Of Measurement URL-------------------------',
  'groupName': 'groupname',
  '//Manage UOM Template URL': '------------------Manage UOM Template URL-------------------------',
  'manageUomTemplate': 'api/uomtemplate',
  'manageUomDefaultTemplate': 'api/UOMTemplate/UpdateUserDefaultTemplate',
  'defaultUserTemplate': 'GetUserDefaultTemplateByUser',
  '//Manage UOM Variable URL': '------------------Manage UOM Variable URL-------------------------',
  'manageUomVariable': 'api/UOMVariable',
  'uomVariableCategory': 'UOMVariableCategory',
  'uomManageVariable': 'api/UOMTemplateVariable',
  'manageVariableAsync': 'GetManageVariablesAsync',
  'getUOMUnits': 'GetUOMUnits',
  'updateManageTemplateVariable': 'UpdateManageTemplateVariable',
  '//Feed Stock create': '------------------Feed Stock create URL-------------------------',
  'feedCreate_api_url': 'https://gateway.microserviceone.com/',
  'feed': 'api/Feed',
  'feed_api': '\'api/',
  'getFeedSubCategory': 'GetFeedSubCategory',
  'customer': 'Customer',
  'feedType': 'FeedType',
  'feedCategory': 'FeedCategory',
  'findCustomer': 'FindCustomer',
  'feedStatus': 'FeedStatus',
  '//Report and Graph': '------------------Report and Graph-------------------------',
  'report': 'api/Report',
  'graph': 'api/Graph',
  'chart_api_url': 'https://gateway.microserviceone.com/',
  'chart': 'api/Chart',
  'getCharts_ByTechnology': 'GetChartsByTechnology',
  'plot_api_url': 'https://gateway.microserviceone.com/',
  'plot': 'api/Plot',
  'getPlots_ByTechnology': 'GetPlotsByTechnology',
  'getUserChart': 'api/UserChart',
  'getUserPlot': 'api/UserPlot',
  'getUserChartTechnologyByUserId': 'GetUserChartTechnologyByUserId',
  'getUserPlotTechnologyByUserId': 'GetUserPlotTechnologyByUserId',
  'login_api_url': 'https://gateway.microserviceone.com/',
  'login': 'api/Authentication/login',
  'logout': 'api/Authentication/Logout',
  '//mode': '-----------------Mode-------------------------',
  'mode_api_url': 'https://gateway.microserviceone.com/',
  'api_ControlMethod': 'api/ControlMethod ',
  'api_ProductObjective': 'api/ProductObjectiveType',
  'api_Sulfinding': 'api/Sulfinding',
  'api_Mode': 'api/Mode',
  'unit ops': '---------------------Unit ops-----------------',
  'unitOps_api_url': 'https://gateway.microserviceone.com/',
  'unitOperation': 'api/UnitOperation',
  'unitOpsFind': 'api/UnitOperation/Find',
  'mptUnitOps': 'api/MPTUnitOperation',
  'activeUnitOperations': 'GetActive',





  'absorbent_api_url': 'https://gateway.microserviceone.com/',
  'absorbent': 'api/Adsorbents',
  'productType': 'GetProductType',
  'productSubType': 'GetproductSubType',
  'sampleType': 'SampleType',
  'binderType': 'BinderType',
  'adsorbentSize': 'AdsorbentSize',
  'adsorbentShape': 'AdsorbentShape',
  'adsorbentCondition': 'AdsorbentCondition',
  'adsorbentHMIS': 'AdsorbentHMIS',
  'product': 'Product',
  'findProduct': 'FindProduct',

  'chemicals': '------------------chemicals-----------------------',
  'chemichals_api_url': 'https://gateway.microserviceone.com/',
  'api_chemicals': 'api/Chemical',
  'api_chemicals_state': 'api/ChemicalState',

  'Inventory - Raw Material': '------------------Inventory - Raw Material-----------------------',
  'inventoryRawMaterial_api_url': 'https://gateway.microserviceone.com/',
  'inventoryRawMaterial': 'api/RawMaterialInventory',
  'inventorySynthesizedMaterial': 'api/SynthesizedMaterialInventory',
  'api_inventory': 'api_inventory',

  'PHD': '------------------PHD-----------------------',
  'phd_api_url': 'https://gateway.microserviceone.com/',
  'phd': 'api/PHD',
  'phdType': 'api/PHDtype'

}
